//! Common
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_IS_SIDEBAR_OPEN = 'SET_IS_SIDEBAR_OPEN';

//! Auth
export const ADMIN_LOGIN = 'ADMIN_LOGIN';

//! Dashboard

//! Master
//* HSN Code
export const GET_HSN_CODE = 'GET_HSN_CODE';
export const SET_HSN_CODE = 'SET_HSN_CODE';
export const CREATE_HSN_CODE = 'CREATE_HSN_CODE';
export const UPDATE_HSN_CODE = 'UPDATE_HSN_CODE';
export const DELETE_HSN_CODE = 'DELETE_HSN_CODE';
export const GET_HSN_CODE_BY_ID = 'GET_HSN_CODE_BY_ID';
export const SET_HSN_CODE_BY_ID = 'SET_HSN_CODE_BY_ID';

//* Sale Area
export const GET_SALE_AREA = 'GET_SALE_AREA';
export const SET_SALE_AREA = 'SET_SALE_AREA';
export const CREATE_SALE_AREA = 'CREATE_SALE_AREA';
export const UPDATE_SALE_AREA = 'UPDATE_SALE_AREA';
export const DELETE_SALE_AREA = 'DELETE_SALE_AREA';
export const GET_SALE_AREA_BY_ID = 'GET_SALE_AREA_BY_ID';
export const SET_SALE_AREA_BY_ID = 'SET_SALE_AREA_BY_ID';

//* Sale Person
export const GET_SALE_PERSON = 'GET_SALE_PERSON';
export const SET_SALE_PERSON = 'SET_SALE_PERSON';
export const CREATE_SALE_PERSON = 'CREATE_SALE_PERSON';
export const UPDATE_SALE_PERSON = 'UPDATE_SALE_PERSON';
export const DELETE_SALE_PERSON = 'DELETE_SALE_PERSON';
export const GET_SALE_PERSON_BY_ID = 'GET_SALE_PERSON_BY_ID';
export const SET_SALE_PERSON_BY_ID = 'SET_SALE_PERSON_BY_ID';

//* Item Category 
export const GET_ITEM_CATEGORY = 'GET_ITEM_CATEGORY';
export const SET_ITEM_CATEGORY = 'SET_ITEM_CATEGORY';
export const CREATE_ITEM_CATEGORY = 'CREATE_ITEM_CATEGORY';
export const UPDATE_ITEM_CATEGORY = 'UPDATE_ITEM_CATEGORY';
export const DELETE_ITEM_CATEGORY = 'DELETE_ITEM_CATEGORY';
export const GET_ITEM_CATEGORY_BY_ID = 'GET_ITEM_CATEGORY_BY_ID';
export const SET_ITEM_CATEGORY_BY_ID = 'SET_ITEM_CATEGORY_BY_ID';

//* Item Packing
export const GET_ITEM_PACKING = 'GET_ITEM_PACKING';
export const SET_ITEM_PACKING = 'SET_ITEM_PACKING';
export const CREATE_ITEM_PACKING = 'CREATE_ITEM_PACKING';
export const UPDATE_ITEM_PACKING = 'UPDATE_ITEM_PACKING';
export const DELETE_ITEM_PACKING = 'DELETE_ITEM_PACKING';
export const GET_ITEM_PACKING_BY_ID = 'GET_ITEM_PACKING_BY_ID';
export const SET_ITEM_PACKING_BY_ID = 'SET_ITEM_PACKING_BY_ID';

//! Setting